# textCNN

In [1]:
## 1.检验阶段

### 1.1引入模块库

In [2]:
from MyModule import Net
import cupy as cp
import numpy 
import pylab

Enjoy NPL MachineLearning


### 1.2生成自定义测试数据集
格式为：3 batch h=9 w=10 channels=1

In [3]:
def loadTestData():        
    x = cp.random.rand(80).reshape(1,8,10,1)
    return x

### 1.3定义网络结构

In [4]:
# 卷积层
conv1 = Net.Conv(kernal=(3,10,1,2),stride=1)

# 激活函数Relu
relu1 = Net.Relu()

# 池化层
max_pooling1 = Net.Pool(ksize=2)

# Flatten 层
flatten1 = Net.Flatten()

# Concat融合
concat1 = Net.Concat()

# 全连接层
fc1 = Net.Fc(6,2)

# softmax
softmax = Net.Softmax()

### 1.4测试网络结构的合理性

#### 1.4.1前向传播

In [5]:
data = loadTestData()
X = data[0:1]
Y = cp.random.randint(1,2,1)%2
print(Y.shape)
print(X.shape)
U = [[[	[0.1],
    [0.1],
    [0.1],
    [0.1],
    [0.1],
    [0.1],
    [0.1],
    [0.1],
    [0.1],
    [0.1]],

    [[0.1],
    [0.1],
    [0.1],
    [0.1],
    [0.1],
    [0.1],
    [0.1],
    [0.1],
    [0.1],
    [0.1]],

    [[0.1],
    [0.1],
    [0.1],
    [0.1],
    [0.1],
    [0.1],
    [0.1],
    [0.1],
    [0.1],
    [0.1]],

    [[0.8],
    [0.8],
    [0.8],
    [0.8],
    [0.8],
    [0.8],
    [0.8],
    [0.8],
    [0.8],
    [0.8]],

    [[0.8],
    [0.8],
    [0.8],
    [0.8],
    [0.8],
    [0.8],
    [0.8],
    [0.8],
    [0.8],
    [0.8]],

    [[0.8],
    [0.8],
    [0.8],
    [0.8],
    [0.8],
    [0.8],
    [0.8],
    [0.8],
    [0.8],
    [0.8]],

      [[0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2]],

      [[0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2]],

      [[0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2]]],
       # ================================
     [[[0.8],
       [0.8],
       [0.8],
       [0.8],
       [0.8],
       [0.8],
       [0.8],
       [0.8],
       [0.8],
       [0.8]],

      [[0.8],
       [0.8],
       [0.8],
       [0.8],
       [0.8],
       [0.8],
       [0.8],
       [0.8],
       [0.8],
       [0.8]],

      [[0.8],
       [0.8],
       [0.8],
       [0.8],
       [0.8],
       [0.8],
       [0.8],
       [0.8],
       [0.8],
       [0.8]],

      [[0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1]],

      [[0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1]],

      [[0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1]],

      [[0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1]],

      [[0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1]],

      [[0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1]]],
       #===========================================
     [[[0.3],
       [0.3],
       [0.3],
       [0.3],
       [0.3],
       [0.3],
       [0.3],
       [0.3],
       [0.3],
       [0.3]],

      [[0.3],
       [0.3],
       [0.3],
       [0.3],
       [0.3],
       [0.3],
       [0.3],
       [0.3],
       [0.3],
       [0.3]],

      [[0.3],
       [0.3],
       [0.3],
       [0.3],
       [0.3],
       [0.3],
       [0.3],
       [0.3],
       [0.3],
       [0.3]],

      [[0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2]],

      [[0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1]],

      [[0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1]],

      [[0.6],
       [0.6],
       [0.6],
       [0.6],
       [0.6],
       [0.6],
       [0.6],
       [0.6],
       [0.6],
       [0.6]],

      [[0.6],
       [0.6],
       [0.6],
       [0.6],
       [0.6],
       [0.6],
       [0.6],
       [0.6],
       [0.6],
       [0.6]],

      [[0.6],
       [0.6],
       [0.6],
       [0.6],
       [0.6],
       [0.6],
       [0.6],
       [0.6],
       [0.6],
       [0.6]]]]
X = cp.array(U) 
X = X[0,:,:,:]
X = X.reshape(1,9,10,1)
Y = cp.array([[1,0]])
print(Y.shape)
print(X.shape)
# for i in range(Y.shape[0]):
#     if Y[i]==0: Y[i]=-1
    # print(Y[i])

(1,)
(1, 8, 10, 1)
(1, 2)
(1, 9, 10, 1)


In [6]:
def Forward(X,Y):
    # 卷积
    forward1 = conv1.forward(X)
    # print(forward1.shape)
    # relu
    forward1 = relu1.forward(forward1)
    # print(forward1.shape)
    # 池化
    forward1 = max_pooling1.forward(forward1)
    # print(forward1.shape)
    # flatten
    forward1 = flatten1.forward(forward1)
    # print(forward1.shape)
    # print(forward2.shape)
    # print(forward3.shape)
    # concate
    # forward = concat1.forward(forward1,forward2,forward3)
    forward = forward1.reshape((1,1,-1))
    # print(forward.shape)
    # 全连接
    forward = fc1.forward(forward)
    # print(forward.shape)
    # softmax
    loss,delta = softmax.calcuteLoss(forward,Y)
    predict = softmax.predict(forward)
    right = 0
    # print(predict.shape)
    for i in range(1):
        # print(f"predict_index-{i}:{cp.argmax(predict[i])+1}")
        if cp.argmax(predict[i])==cp.argmax(Y[i]) :
            right = right + 1
    return loss,delta,right/1
    # print(f"softmax_layer:{delta.shape}" )
    print(f"loss:{loss} delta:{delta}")

#### 1.4.2反向传播

In [7]:
learning_rate = 0.01

In [8]:
def Backward(delta,lr):
        # 全连接
    # print(delta.shape)
    backward = fc1.backward(delta,lr)
    # print(f"fc:{backward.shape}")
    # concate
    #backward1,backward2,backward3 =  concat1.backward(backward) 
    backward1 = backward.reshape((1,-1))
    # print(backward1.shape)
    # print(f"concate:{backward1.shape} {backward2.shape} {backward3.shape}")
    # flatten
    backward1 = flatten1.backward(backward1)
    # print(f"flatten1:{backward1.shape} flatten2:{backward2.shape} flatten3:{backward3.shape}")
    # 池化
    backward1 = max_pooling1.backward(backward1)
    # print(f"pool1:{backward1.shape} pool2:{backward2.shape} pool3:{backward3.shape}")
    # relu
    backward1 = relu1.backward(backward1)
    # 卷积
    backward1 = conv1.backward(backward1,lr)
    # print(f"反向传播完成")

#### 1.4.3前期

In [9]:
for i in range(1):
    data = loadTestData()
       
    loss,delta,right_rate= Forward(X,Y)
    Backward(delta,0.05)
    print("=================================================\n")
    print(f"delta_shape:{delta.shape}")
    print(f"epoch:{i}/{100} loss:{loss} right_rate :{right_rate} softmax:{softmax.softmax}")


delta_shape:(1, 2)
epoch:0/100 loss:0.09190524827134693 right_rate :1.0 softmax:[[0.91218158 0.08781842]]


全连接层

In [10]:
print(f"k:\n{fc1.k}")
print(f"b:\n{fc1.b}")
print(f"k_gradient:\n{fc1.k_gradient}")
print(f"b_gradient:\n{fc1.b_gradient}")
print(f"output:{fc1.forward(fc1.x)}")

k:
[[-0.76978017  0.4245765 ]
 [ 1.33789619 -0.43957177]
 [-1.82779161 -1.20568428]
 [ 1.00962028 -0.31965773]
 [-0.3938102   0.33762573]
 [ 0.68704183 -0.30978048]]
b:
[ 0.36999043 -0.58513771]
k_gradient:
[[ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]
 [-0.12438063  0.12438063]]
b_gradient:
[-0.08781842  0.08781842]
output:[[ 1.34307434 -1.02389177]]


flatten层

In [11]:
print(f"input:\n{flatten1.x}")
print(f"output:\n{flatten1.forward(flatten1.x)}")

input:
[[[[0.         0.        ]]

  [[0.         0.        ]]

  [[0.         1.41633868]]]]
output:
[[[0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [0.        ]
  [1.41633868]]]


最大池化层

In [12]:
print(f"input:\n{max_pooling1.x}")
print(f"output:\n{max_pooling1.forward(max_pooling1.x)}")

input:
[[[[0.         0.        ]]

  [[0.         0.        ]]

  [[0.         0.        ]]

  [[0.         0.        ]]

  [[0.         0.25312087]]

  [[0.         1.41633868]]

  [[0.         0.        ]]]]
output:
[[[[0.         0.        ]]

  [[0.         0.        ]]

  [[0.         1.41633868]]]]


卷积层

In [13]:
print(f"k:\n{conv1.kernal}")
print(f"b:\n{conv1.b}")
print(f"k_gradient:\n{conv1.k_gradient}")
print(f"b_gradient:\n{conv1.b_gradient}")

k:
[[[[ 0.13078032 -0.3573856 ]]

  [[ 0.14005123  0.91068007]]

  [[ 0.60711949 -0.69716548]]

  [[ 0.71783364  1.66256131]]

  [[-0.63095416  0.13525836]]

  [[-0.32166293 -1.79275959]]

  [[-1.44194153  1.99974009]]

  [[ 0.45558489  0.28540531]]

  [[-0.60965279  0.94426077]]

  [[-1.04076393  0.21591289]]]


 [[[ 1.78234647 -0.43669316]]

  [[-0.56724726  1.27316257]]

  [[-0.6970224   0.16262075]]

  [[-1.48280072 -1.49222752]]

  [[-1.17896374 -1.20088641]]

  [[-1.50605606  0.11670766]]

  [[ 1.26496178 -0.41599527]]

  [[ 0.13714922 -0.09797643]]

  [[-0.27873839 -0.27457789]]

  [[ 0.71920713  0.43581406]]]


 [[[-0.75392347  0.89400339]]

  [[-0.48255052 -1.8760723 ]]

  [[ 0.1182989  -0.24549273]]

  [[-0.80128164 -0.14313734]]

  [[ 0.26381514  0.86562813]]

  [[-2.09676267 -0.60541175]]

  [[ 1.25511355 -0.35838073]]

  [[ 0.28836312 -0.10438464]]

  [[ 1.1034645  -1.49464974]]

  [[-1.58326225  0.63744058]]]]
b:
[-0.41649527 -0.32132278]
k_gradient:
[[[[ 1.00000000e-09 -

#### 1.4.4 后期

In [14]:
lr = 0.01
img_x = []
loss_y = []
right_y = []
last_loss = 1e5
for i in range(501):
    # data = loadTestData()
    # lr *= 0.99**((i+1)//10)
    loss,delta,right_rate= Forward(X,Y)
    Backward(delta,lr)

    
    # pylab.plot(cp.asnumpy(img_x),cp.asnumpy(loss_y))
    # pylab.plot(img_x,right_y)
    print(f"epoch:{i}/{100} loss:{loss} right_rate :{right_rate} softmax:{softmax.softmax}")
    if (last_loss-loss<-0.2) : break 

epoch:0/100 loss:0.08663441834896105 right_rate :1.0 softmax:[[0.91700228 0.08299772]]
epoch:1/100 loss:0.08564904302472386 right_rate :1.0 softmax:[[0.91790632 0.08209368]]
epoch:2/100 loss:0.0846797078275536 right_rate :1.0 softmax:[[0.91879652 0.08120348]]
epoch:3/100 loss:0.08372610623874888 right_rate :1.0 softmax:[[0.91967312 0.08032688]]
epoch:4/100 loss:0.08278793772787123 right_rate :1.0 softmax:[[0.92053634 0.07946366]]
epoch:5/100 loss:0.08186490765843261 right_rate :1.0 softmax:[[0.92138642 0.07861358]]
epoch:6/100 loss:0.08095672719343484 right_rate :1.0 softmax:[[0.9222236 0.0777764]]
epoch:7/100 loss:0.08006311320087263 right_rate :1.0 softmax:[[0.92304809 0.07695191]]
epoch:8/100 loss:0.07918378815930786 right_rate :1.0 softmax:[[0.92386011 0.07613989]]
epoch:9/100 loss:0.07831848006361439 right_rate :1.0 softmax:[[0.92465989 0.07534011]]
epoch:10/100 loss:0.07746692233098636 right_rate :1.0 softmax:[[0.92544764 0.07455236]]
epoch:11/100 loss:0.07662885370729924 right_r

全连接层

In [15]:
print(f"k:\n{fc1.k}")
print(f"b:\n{fc1.b}")
print(f"k_gradient:\n{fc1.k_gradient}")
print(f"b_gradient:\n{fc1.b_gradient}")

k:
[[-0.76978017  0.4245765 ]
 [ 1.33789619 -0.43957177]
 [-1.82779161 -1.20568428]
 [ 1.0130138  -0.32305126]
 [-0.3938102   0.33762573]
 [ 0.89720509 -0.51994374]]
b:
[ 0.47757981 -0.69272709]
k_gradient:
[[ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]
 [-0.00181611  0.00181611]
 [ 0.          0.        ]
 [-0.00914251  0.00914251]]
b_gradient:
[-0.00341309  0.00341309]


flatten层

In [16]:
print(f"input:\n{flatten1.x}")
print(f"output:\n{flatten1.forward(flatten1.x)}")

input:
[[[[0.         0.        ]]

  [[0.         0.53210267]]

  [[0.         2.67866444]]]]
output:
[[[0.        ]
  [0.        ]
  [0.        ]
  [0.53210267]
  [0.        ]
  [2.67866444]]]


最大池化层

In [17]:
print(f"input:\n{max_pooling1.x}")
print(f"output:\n{max_pooling1.forward(max_pooling1.x)}")

input:
[[[[0.00000000e+00 0.00000000e+00]]

  [[0.00000000e+00 0.00000000e+00]]

  [[0.00000000e+00 0.00000000e+00]]

  [[0.00000000e+00 5.32102668e-01]]

  [[0.00000000e+00 1.75550520e+00]]

  [[0.00000000e+00 2.67866444e+00]]

  [[0.00000000e+00 5.10062982e-04]]]]
output:
[[[[0.         0.        ]]

  [[0.         0.53210267]]

  [[0.         2.67866444]]]]


卷积层

In [18]:
print(f"k:\n{conv1.kernal}")
print(f"b:\n{conv1.b}")
print(f"k_gradient:\n{conv1.k_gradient}")
print(f"b_gradient:\n{conv1.b_gradient}")

k:
[[[[ 0.13078031 -0.24160218]]

  [[ 0.14005123  1.02646349]]

  [[ 0.60711948 -0.58138206]]

  [[ 0.71783363  1.77834473]]

  [[-0.63095416  0.25104178]]

  [[-0.32166294 -1.67697617]]

  [[-1.44194153  2.11552351]]

  [[ 0.45558488  0.40118873]]

  [[-0.6096528   1.06004419]]

  [[-1.04076393  0.3316963 ]]]


 [[[ 1.78234646 -0.39750172]]

  [[-0.56724727  1.31235402]]

  [[-0.6970224   0.2018122 ]]

  [[-1.48280073 -1.45303607]]

  [[-1.17896374 -1.16169497]]

  [[-1.50605606  0.15589911]]

  [[ 1.26496178 -0.37680383]]

  [[ 0.13714922 -0.05878499]]

  [[-0.27873839 -0.23538645]]

  [[ 0.71920712  0.4750055 ]]]


 [[[-0.75392348  0.93319483]]

  [[-0.48255052 -1.83688086]]

  [[ 0.11829889 -0.20630129]]

  [[-0.80128164 -0.1039459 ]]

  [[ 0.26381514  0.90481957]]

  [[-2.09676268 -0.56622031]]

  [[ 1.25511355 -0.31918929]]

  [[ 0.28836312 -0.0651932 ]]

  [[ 1.1034645  -1.45545829]]

  [[-1.58326225  0.67663202]]]]
b:
[-0.41649527 -0.17659351]
k_gradient:
[[[[ 1.00000000e-09 -