# textCNN

In [1]:
## 1.检验阶段

### 1.1引入模块库

In [2]:
from MyModule import Net
import cupy as cp
import numpy 
import pylab

Enjoy NPL MachineLearning


### 1.2生成自定义测试数据集
格式为：3 batch h=9 w=10 channels=1

In [3]:
def loadTestData():        
    x = cp.random.rand(80).reshape(1,8,10,1)
    return x

### 1.3定义网络结构

In [4]:
# 卷积层
conv1 = Net.Conv(kernal=(3,10,1,2),stride=1)

# 激活函数Relu
relu1 = Net.Relu()

# 池化层
max_pooling1 = Net.Pool(ksize=2)

# Flatten 层
flatten1 = Net.Flatten()

# Concat融合
concat1 = Net.Concat()

# 全连接层
fc1 = Net.Fc(6,2)

# softmax
softmax = Net.Softmax()

### 1.4测试网络结构的合理性

#### 1.4.1前向传播

In [5]:
data = loadTestData()
X = data[0:1]
Y = cp.random.randint(1,2,1)%2
print(Y.shape)
print(X.shape)
U = [[[	[0.1],
    [0.1],
    [0.1],
    [0.1],
    [0.1],
    [0.1],
    [0.1],
    [0.1],
    [0.1],
    [0.1]],

    [[0.1],
    [0.1],
    [0.1],
    [0.1],
    [0.1],
    [0.1],
    [0.1],
    [0.1],
    [0.1],
    [0.1]],

    [[0.1],
    [0.1],
    [0.1],
    [0.1],
    [0.1],
    [0.1],
    [0.1],
    [0.1],
    [0.1],
    [0.1]],

    [[0.8],
    [0.8],
    [0.8],
    [0.8],
    [0.8],
    [0.8],
    [0.8],
    [0.8],
    [0.8],
    [0.8]],

    [[0.8],
    [0.8],
    [0.8],
    [0.8],
    [0.8],
    [0.8],
    [0.8],
    [0.8],
    [0.8],
    [0.8]],

    [[0.8],
    [0.8],
    [0.8],
    [0.8],
    [0.8],
    [0.8],
    [0.8],
    [0.8],
    [0.8],
    [0.8]],

      [[0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2]],

      [[0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2]],

      [[0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2]]],
       # ================================
     [[[0.8],
       [0.8],
       [0.8],
       [0.8],
       [0.8],
       [0.8],
       [0.8],
       [0.8],
       [0.8],
       [0.8]],

      [[0.8],
       [0.8],
       [0.8],
       [0.8],
       [0.8],
       [0.8],
       [0.8],
       [0.8],
       [0.8],
       [0.8]],

      [[0.8],
       [0.8],
       [0.8],
       [0.8],
       [0.8],
       [0.8],
       [0.8],
       [0.8],
       [0.8],
       [0.8]],

      [[0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1]],

      [[0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1]],

      [[0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1]],

      [[0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1]],

      [[0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1]],

      [[0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1]]],
       #===========================================
     [[[0.3],
       [0.3],
       [0.3],
       [0.3],
       [0.3],
       [0.3],
       [0.3],
       [0.3],
       [0.3],
       [0.3]],

      [[0.3],
       [0.3],
       [0.3],
       [0.3],
       [0.3],
       [0.3],
       [0.3],
       [0.3],
       [0.3],
       [0.3]],

      [[0.3],
       [0.3],
       [0.3],
       [0.3],
       [0.3],
       [0.3],
       [0.3],
       [0.3],
       [0.3],
       [0.3]],

      [[0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2]],

      [[0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1]],

      [[0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1],
       [0.1]],

      [[0.6],
       [0.6],
       [0.6],
       [0.6],
       [0.6],
       [0.6],
       [0.6],
       [0.6],
       [0.6],
       [0.6]],

      [[0.6],
       [0.6],
       [0.6],
       [0.6],
       [0.6],
       [0.6],
       [0.6],
       [0.6],
       [0.6],
       [0.6]],

      [[0.6],
       [0.6],
       [0.6],
       [0.6],
       [0.6],
       [0.6],
       [0.6],
       [0.6],
       [0.6],
       [0.6]]]]
X = cp.array(U) 
X = X[0,:,:,:]
X = X.reshape(1,9,10,1)
Y = cp.array([[0,1]])
print(Y.shape)
print(X.shape)
# for i in range(Y.shape[0]):
#     if Y[i]==0: Y[i]=-1
    # print(Y[i])

(1,)
(1, 8, 10, 1)
(1, 2)
(1, 9, 10, 1)


In [6]:
def Forward(X,Y):
    # 卷积
    forward1 = conv1.forward(X)
    # print(forward1.shape)
    # relu
    forward1 = relu1.forward(forward1)
    # print(forward1.shape)
    # 池化
    forward1 = max_pooling1.forward(forward1)
    # print(forward1.shape)
    # flatten
    forward1 = flatten1.forward(forward1)
    # print(forward1.shape)
    # print(forward2.shape)
    # print(forward3.shape)
    # concate
    # forward = concat1.forward(forward1,forward2,forward3)
    forward = forward1.reshape((1,1,-1))
    # print(forward.shape)
    # 全连接
    forward = fc1.forward(forward)
    # print(forward.shape)
    # softmax
    loss,delta = softmax.calcuteLoss(forward,Y)
    predict = softmax.predict(forward)
    right = 0
    # print(predict.shape)
    for i in range(1):
        # print(f"predict_index-{i}:{cp.argmax(predict[i])+1}")
        if cp.argmax(predict[i])==cp.argmax(Y[i]) :
            right = right + 1
    return loss,delta,right/1
    # print(f"softmax_layer:{delta.shape}" )
    print(f"loss:{loss} delta:{delta}")

#### 1.4.2反向传播

In [7]:
learning_rate = 0.01

In [8]:
def Backward(delta,lr):
        # 全连接
    # print(delta.shape)
    backward = fc1.backward(delta,lr)
    # print(f"fc:{backward.shape}")
    # concate
    #backward1,backward2,backward3 =  concat1.backward(backward) 
    backward1 = backward.reshape((1,-1))
    # print(backward1.shape)
    # print(f"concate:{backward1.shape} {backward2.shape} {backward3.shape}")
    # flatten
    backward1 = flatten1.backward(backward1)
    # print(f"flatten1:{backward1.shape} flatten2:{backward2.shape} flatten3:{backward3.shape}")
    # 池化
    backward1 = max_pooling1.backward(backward1)
    # print(f"pool1:{backward1.shape} pool2:{backward2.shape} pool3:{backward3.shape}")
    # relu
    backward1 = relu1.backward(backward1)
    # 卷积
    backward1 = conv1.backward(backward1,lr)
    # print(f"反向传播完成")

#### 1.4.3前期

In [9]:
for i in range(1):
    data = loadTestData()
       
    loss,delta,right_rate= Forward(X,Y)
    Backward(delta,0.05)
    print("=================================================\n")
    print(f"delta_shape:{delta.shape}")
    print(f"epoch:{i}/{100} loss:{loss} right_rate :{right_rate} softmax:{softmax.softmax}")


delta_shape:(1, 2)
epoch:0/100 loss:5.995419870186056 right_rate :0.0 softmax:[[0.99751987 0.00248013]]


全连接层

In [10]:
print(f"k:\n{fc1.k}")
print(f"b:\n{fc1.b}")
print(f"k_gradient:\n{fc1.k_gradient}")
print(f"b_gradient:\n{fc1.b_gradient}")
print(f"output:{fc1.forward(fc1.x)}")

k:
[[ 1.27929813  1.00848862]
 [-1.3359753  -0.3761078 ]
 [-0.38455038 -1.94049518]
 [-0.00986547 -0.16730764]
 [-0.45914213 -0.02790412]
 [ 0.54554595 -2.32796785]]
b:
[-0.26234327  1.40359751]
k_gradient:
[[ 4.09438781 -4.09438781]
 [ 0.          0.        ]
 [ 2.66374666 -2.66374666]
 [ 0.          0.        ]
 [ 0.23288641 -0.23288641]
 [ 0.          0.        ]]
b_gradient:
[ 0.99751987 -0.99751987]
output:[[3.85453702 0.35465348]]


flatten层

In [11]:
print(f"input:\n{flatten1.x}")
print(f"output:\n{flatten1.forward(flatten1.x)}")

input:
[[[[4.10456768 0.        ]]

  [[2.67036953 0.        ]]

  [[0.23346544 0.        ]]]]
output:
[[[4.10456768]
  [0.        ]
  [2.67036953]
  [0.        ]
  [0.23346544]
  [0.        ]]]


最大池化层

In [12]:
print(f"input:\n{max_pooling1.x}")
print(f"output:\n{max_pooling1.forward(max_pooling1.x)}")

input:
[[[[1.0550538  0.        ]]

  [[4.10456768 0.        ]]

  [[2.67036953 0.        ]]

  [[1.61802178 0.        ]]

  [[0.         0.        ]]

  [[0.23346544 0.        ]]

  [[1.13547779 0.        ]]]]
output:
[[[[4.10456768 0.        ]]

  [[2.67036953 0.        ]]

  [[0.23346544 0.        ]]]]


卷积层

In [13]:
print(f"k:\n{conv1.kernal}")
print(f"b:\n{conv1.b}")
print(f"k_gradient:\n{conv1.k_gradient}")
print(f"b_gradient:\n{conv1.b_gradient}")

k:
[[[[ 0.58467676 -0.20960342]]

  [[ 0.06148849  0.34466844]]

  [[-0.56847766 -0.44564024]]

  [[-0.26994449  0.46861915]]

  [[-0.012154    0.48361147]]

  [[ 0.52724816 -2.45643644]]

  [[-0.38949528 -0.64499792]]

  [[-0.23305436  2.82012379]]

  [[-0.40432753 -0.29426781]]

  [[-0.76135702 -1.33409982]]]


 [[[ 0.5764105  -0.31576252]]

  [[-0.08264553  0.25207784]]

  [[-0.30525857 -0.11191072]]

  [[-1.39695637  1.30695695]]

  [[ 0.19467876  1.23501087]]

  [[-1.2399618  -0.44275911]]

  [[ 0.10003944 -1.43964695]]

  [[-0.46526408 -1.21698424]]

  [[ 0.52176207  0.80362514]]

  [[-0.67201318  0.93216246]]]


 [[[ 0.91030387  0.81579619]]

  [[-1.03733368  0.76029978]]

  [[ 0.31921258 -0.3429984 ]]

  [[-0.42792111 -0.34603032]]

  [[ 0.34741314  1.09928791]]

  [[-0.61070404 -0.68885699]]

  [[ 1.3437621  -0.46237423]]

  [[ 2.4960262  -0.07730748]]

  [[-0.77927259 -0.08554727]]

  [[ 0.83711126 -2.87185968]]]]
b:
[0.87015863 0.10659187]
k_gradient:
[[[[-7.59139734e-02  1.

#### 1.4.4 后期

In [14]:
lr = 0.01
img_x = []
loss_y = []
right_y = []
last_loss = 1e5
for i in range(501):
    # data = loadTestData()
    # lr *= 0.99**((i+1)//10)
    loss,delta,right_rate= Forward(X,Y)
    Backward(delta,lr)

    
    # pylab.plot(cp.asnumpy(img_x),cp.asnumpy(loss_y))
    # pylab.plot(img_x,right_y)
    print(f"epoch:{i}/{100} loss:{loss} right_rate :{right_rate} softmax:{softmax.softmax}")
    if (last_loss-loss<-0.2) : break 

epoch:0/100 loss:1.3878010441829323 right_rate :0.0 softmax:[[0.75038639 0.24961361]]
epoch:1/100 loss:1.045307245322588 right_rate :0.0 softmax:[[0.64842622 0.35157378]]
epoch:2/100 loss:0.8076648521293884 right_rate :0.0 softmax:[[0.55411191 0.44588809]]
epoch:3/100 loss:0.6434216049782746 right_rate :1.0 softmax:[[0.47451868 0.52548132]]
epoch:4/100 loss:0.5278427418619899 right_rate :1.0 softmax:[[0.41013389 0.58986611]]
epoch:5/100 loss:0.4442032130801314 right_rate :1.0 softmax:[[0.35867492 0.64132508]]
epoch:6/100 loss:0.38183926738944707 right_rate :1.0 softmax:[[0.31740524 0.68259476]]
epoch:7/100 loss:0.3340132143308308 right_rate :1.0 softmax:[[0.28396568 0.71603432]]
epoch:8/100 loss:0.2964061847504391 right_rate :1.0 softmax:[[0.25652463 0.74347537]]
epoch:9/100 loss:0.26618271302766966 right_rate :1.0 softmax:[[0.2337109 0.7662891]]
epoch:10/100 loss:0.24143090767356187 right_rate :1.0 softmax:[[0.21450693 0.78549307]]
epoch:11/100 loss:0.2208272381673775 right_rate :1.0 

全连接层

In [15]:
print(f"k:\n{fc1.k}")
print(f"b:\n{fc1.b}")
print(f"k_gradient:\n{fc1.k_gradient}")
print(f"b_gradient:\n{fc1.b_gradient}")

k:
[[ 0.70776208  1.58002466]
 [-1.3359753  -0.3761078 ]
 [-0.42043357 -1.90461199]
 [-0.00986547 -0.16730764]
 [-0.45914213 -0.02790412]
 [ 0.54554595 -2.32796785]]
b:
[-0.48539094  1.62664517]
k_gradient:
[[ 3.20314874e-02 -3.20314874e-02]
 [ 0.00000000e+00  0.00000000e+00]
 [ 6.56117069e-06 -6.56117069e-06]
 [ 0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00]]
b_gradient:
[ 0.01225216 -0.01225216]


flatten层

In [16]:
print(f"input:\n{flatten1.x}")
print(f"output:\n{flatten1.forward(flatten1.x)}")

input:
[[[[2.61435495e+00 0.00000000e+00]]

  [[5.35511475e-04 0.00000000e+00]]

  [[0.00000000e+00 0.00000000e+00]]]]
output:
[[[2.61435495e+00]
  [0.00000000e+00]
  [5.35511475e-04]
  [0.00000000e+00]
  [0.00000000e+00]
  [0.00000000e+00]]]


最大池化层

In [17]:
print(f"input:\n{max_pooling1.x}")
print(f"output:\n{max_pooling1.forward(max_pooling1.x)}")

input:
[[[[5.74875280e-01 0.00000000e+00]]

  [[2.61435495e+00 0.00000000e+00]]

  [[5.35511475e-04 0.00000000e+00]]

  [[0.00000000e+00 0.00000000e+00]]

  [[0.00000000e+00 0.00000000e+00]]

  [[0.00000000e+00 0.00000000e+00]]

  [[3.40223851e-01 0.00000000e+00]]]]
output:
[[[[2.61435495e+00 0.00000000e+00]]

  [[5.35511475e-04 0.00000000e+00]]

  [[0.00000000e+00 0.00000000e+00]]]]


卷积层

In [18]:
print(f"k:\n{conv1.kernal}")
print(f"b:\n{conv1.b}")
print(f"k_gradient:\n{conv1.k_gradient}")
print(f"b_gradient:\n{conv1.b_gradient}")

k:
[[[[ 0.57860606 -0.20960343]]

  [[ 0.05541779  0.34466843]]

  [[-0.57454836 -0.44564025]]

  [[-0.27601519  0.46861914]]

  [[-0.0182247   0.48361146]]

  [[ 0.52117745 -2.45643645]]

  [[-0.39556599 -0.64499793]]

  [[-0.23912506  2.82012378]]

  [[-0.41039823 -0.29426781]]

  [[-0.76742772 -1.33409982]]]


 [[[ 0.4797938  -0.31576253]]

  [[-0.17926222  0.25207783]]

  [[-0.40187527 -0.11191073]]

  [[-1.49357307  1.30695694]]

  [[ 0.09806206  1.23501087]]

  [[-1.33657849 -0.44275911]]

  [[ 0.00342274 -1.43964696]]

  [[-0.56188078 -1.21698425]]

  [[ 0.42514537  0.80362514]]

  [[-0.76862988  0.93216246]]]


 [[[ 0.8617383   0.81579619]]

  [[-1.08589926  0.76029978]]

  [[ 0.27064701 -0.3429984 ]]

  [[-0.47648669 -0.34603032]]

  [[ 0.29884756  1.09928791]]

  [[-0.65926961 -0.68885699]]

  [[ 1.29519652 -0.46237424]]

  [[ 2.44746063 -0.07730749]]

  [[-0.82783816 -0.08554727]]

  [[ 0.78854568 -2.87185969]]]]
b:
[0.80945166 0.10659187]
k_gradient:
[[[[7.50514954e-04 1.00